node {
    def mvnHome
    stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
        //git 'https://github.com/mpmunasinghe/pipeline-plumber.git'
        git branch: 'main', url: 'https://github.com/mpmunasinghe/pipeline-plumber'
        // Get the Maven tool.
        // ** NOTE: This 'M3' Maven tool must be configured
        // **       in the global configuration.
        mvnHome = tool 'Maven'
    }
    stage('Build') {
        tool name: 'OpenJDK-11', type: 'jdk'

        sh 'java -version'
        // Run the maven build
        //def job = build job: 'pipeline-plumber-build'
                withEnv(["MVN_HOME=$mvnHome"]) {
            if (isUnix()) {
                sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore dependency:purge-local-repository clean install'
            } else {
                bat(/"%MVN_HOME%\bin\mvn" -Dmaven.test.failure.ignore dependency:purge-local-repository clean install/)
            }
        }
    }
    stage('Image: Push') {
        docker.withRegistry('https://registry.hub.docker.com/pipeplumber/', 'dockerhub_id') {
            def customImage = docker.build("pipeplumber/plumber:0.0.1")
            customImage.push()
        }
    }
    stage('Results') {
        //junit '**/target/surefire-reports/TEST-*.xml'
        archiveArtifacts 'target/*.jar'
        echo "Hello Success"
    }
}

